### ISSUE TITLE
LORAWAN

### ISSUE THREAD

**Issue by genoinosonda** [Inteform/esp32-lora-library#1]
Good afternoon.

Thanks for the availability of the source code, we ran some tests and we were successful.

One single question, do you have any implementation (or do you intend to) of the Lorawan protocol using the ESP-IDF?

Thank you.

**Comment by bruabas** [comment]
Hi. Yes, the idea of LoraWAN implementation on ESP-32 is very interesting, and I don't know about any.
But it will be a higher protocol layer, above this one.
Any help is very welcome!
